### ISSUE TITLE
[Submission]: Pipe Dreams 3D

### ISSUE THREAD

**Issue by geotrev** [geotrev/afew.games#260]
### TODO

- [x] Add to database
- [x] Add credit

### Title

Pipe Dreams 3D

### Platform

PlayStation

### MPN (Manufacturer's Part Number)

SLUS-01409

### Country

USA

### Additional Information

Compare the UPCs on these two copies:
1 - https://www.ebay.com/itm/395075464601?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=3oZhjL47SZ2&sssrc=4429486&ssuid=wVZl_VM-TW-&var=&widget_ver=artemis&media=COPY

2 - https://www.ebay.com/itm/126160747014?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=bSIccmP2Q5W&sssrc=4429486&ssuid=wVZl_VM-TW-&var=&widget_ver=artemis&media=COPY

### Credit

Bird Dog Gaming

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by geotrev** [comment]
![IMG_7221](https://github.com/geotrev/afew.games/assets/3946669/69bfff96-6ff8-4cfe-b5d6-76369c2becbb)
![IMG_7219](https://github.com/geotrev/afew.games/assets/3946669/47071a4b-fd12-4a0f-9791-cc0c7316cefe)
![IMG_7222](https://github.com/geotrev/afew.games/assets/3946669/4df8ba64-1ea6-47d4-884e-453146592edf)

**Comment by geotrev** [comment]
- [x] Added to database
- [x] Credit added
